export const styles = {
  container: {
    minHeight: '100vh',
    backgroundColor: 'rgb(249, 250, 251)',
  },
  nav: {
    backgroundColor: 'white',
    borderBottom: '1px solid rgb(229, 231, 235)',
    padding: '1rem 1.5rem',
  },
  navContent: {
    maxWidth: '80rem',
    margin: '0 auto',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  logo: {
    display: 'flex',
    alignItems: 'center',
    gap: '0.5rem',
    textDecoration: 'none',
  },
  logoIcon: {
    width: '2rem',
    height: '2rem',
    borderRadius: '50%',
    background: 'linear-gradient(to bottom right, rgb(192, 132, 252), rgb(147, 51, 234))',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
  },
  logoIconInner: {
    width: '1.25rem',
    height: '1.25rem',
    borderRadius: '50%',
    backgroundColor: 'rgba(255, 255, 255, 0.3)',
  },
  logoText: {
    fontSize: '1.25rem',
    fontWeight: 700,
    color: 'rgb(17, 24, 39)',
  },
  userSection: {
    display: 'flex',
    alignItems: 'center',
    gap: '0.75rem',
    padding: '0.5rem 0.75rem',
  },
  userAvatar: {
    width: '2.5rem',
    height: '2.5rem',
    borderRadius: '50%',
    backgroundColor: 'rgb(209, 213, 219)',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
  },
  userIcon: {
    width: '1.5rem',
    height: '1.5rem',
    color: 'rgb(75, 85, 99)',
  },
  userInfo: {
    textAlign: 'left' as const,
  },
  userName: {
    fontSize: '0.875rem',
    fontWeight: 600,
    color: 'rgb(17, 24, 39)',
  },
  userAccount: {
    fontSize: '0.75rem',
    color: 'rgb(107, 114, 128)',
  },
  mainContent: {
    maxWidth: '80rem',
    margin: '0 auto',
    padding: '2rem 1.5rem',
  },
  headerSection: {
    display: 'flex',
    alignItems: 'flex-start',
    justifyContent: 'flex-end',
    marginBottom: '2rem',
  },
  uploadButton: {
    padding: '0.75rem 1.5rem',
    backgroundColor: 'rgb(147, 51, 234)',
    color: 'white',
    borderRadius: '0.5rem',
    fontWeight: 600,
    display: 'flex',
    alignItems: 'center',
    gap: '0.5rem',
    cursor: 'pointer',
    border: 'none',
  },
  uploadIcon: {
    width: '1.25rem',
    height: '1.25rem',
  },
  documentsTitle: {
    fontSize: '2.25rem',
    fontWeight: 700,
    color: 'rgb(17, 24, 39)',
    marginBottom: '1.5rem',
  },
  filterSection: {
    display: 'flex',
    alignItems: 'center',
    gap: '1rem',
    marginBottom: '1.5rem',
  },
  filterButton: {
    display: 'flex',
    alignItems: 'center',
    gap: '0.5rem',
    padding: '0.5rem 1rem',
    borderRadius: '0.5rem',
    border: 'none',
    cursor: 'pointer',
    fontWeight: 500,
  },
  filterIcon: {
    width: '1.25rem',
    height: '1.25rem',
  },
  filterControls: {
    marginLeft: 'auto',
    display: 'flex',
    alignItems: 'center',
    gap: '1rem',
  },
  select: {
    padding: '0.5rem 1rem',
    border: '1px solid rgb(209, 213, 219)',
    borderRadius: '0.5rem',
    backgroundColor: 'white',
  },
  searchInput: {
    padding: '0.5rem 1rem',
    border: '1px solid rgb(209, 213, 219)',
    borderRadius: '0.5rem',
    backgroundColor: 'white',
    width: '16rem',
  },
  tableContainer: {
    backgroundColor: 'white',
    border: '2px solid rgb(229, 231, 235)',
    borderRadius: '0.5rem',
    overflow: 'visible',
  },
  table: {
    width: '100%',
  },
  tableHead: {
    backgroundColor: 'rgb(249, 250, 251)',
    borderBottom: '1px solid rgb(229, 231, 235)',
  },
  tableHeader: {
    padding: '1rem 1.5rem',
    textAlign: 'left' as const,
    fontSize: '0.875rem',
    fontWeight: 600,
    color: 'rgb(75, 85, 99)',
  },
  tableCell: {
    padding: '1rem 1.5rem',
    fontSize: '0.875rem',
  },
  editButton: {
    padding: '0.5rem 1rem',
    backgroundColor: 'rgb(134, 239, 172)',
    color: 'rgb(17, 24, 39)',
    borderRadius: '0.5rem',
    fontWeight: 600,
    display: 'flex',
    alignItems: 'center',
    gap: '0.25rem',
    border: 'none',
    cursor: 'pointer',
  },
  menuButton: {
    padding: '0.5rem',
    border: 'none',
    backgroundColor: 'transparent',
    borderRadius: '0.5rem',
    cursor: 'pointer',
  },
  menuIcon: {
    width: '1.25rem',
    height: '1.25rem',
    color: 'rgb(75, 85, 99)',
  },
  dropdown: {
    position: 'absolute' as const,
    right: 0,
    marginTop: '0.5rem',
    width: '12rem',
    backgroundColor: 'white',
    border: '1px solid rgb(229, 231, 235)',
    borderRadius: '0.5rem',
    boxShadow: '0 10px 15px -3px rgba(0, 0, 0, 0.1)',
    zIndex: 10,
  },
  dropdownButton: {
    width: '100%',
    padding: '0.75rem 1rem',
    textAlign: 'left' as const,
    fontSize: '0.875rem',
    display: 'flex',
    alignItems: 'center',
    gap: '0.5rem',
    border: 'none',
    backgroundColor: 'transparent',
    cursor: 'pointer',
  },
  paginationContainer: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginTop: '1rem',
  },
  paginationText: {
    fontSize: '0.875rem',
    color: 'rgb(75, 85, 99)',
  },
  paginationControls: {
    display: 'flex',
    alignItems: 'center',
    gap: '1rem',
  },
  paginationButton: {
    padding: '0.5rem',
    border: 'none',
    backgroundColor: 'transparent',
    borderRadius: '0.5rem',
    cursor: 'pointer',
  },
};
